gcc_machine:
  - armv7l
gcc_vendor:
  - conda
gcc_version:
  # - 8.5.0
  # - 9.5.0
  # - 10.4.0
  # - 11.3.0
  - 12.2.0
gcc_maj_ver:
  # - 8
  # - 9
  # - 10
  # - 11
  - 12
libgfortran_soname:
  # - 5
  # - 5
  # - 5
  # - 5
  - 5
binutils_version:
  - 2.40
cross_target_platform:
  - linux-armv7l
old_gcc_vendor:
  - conda_cos7
glibc_version:
  - 2.17
# openmp versions
openmp_ver:
  - 4.5
libgomp_ver:
  - 1.0.0
_libgcc_mutex:
  - 0.1 conda_forge
use_system_gcc:
  - False
zip_keys:
  - - glibc_version
    - old_gcc_vendor
    - gcc_machine
    - cross_target_platform
  - - gcc_version
    - gcc_maj_ver
    - libgfortran_soname

channel_sources:
- e8035669acarmv7,conda-forge
channel_targets:
- e8035669acarmv7 main
docker_image:
- e8035669/linux-anvil-armv7l # [os.environ.get("BUILD_PLATFORM") == "linux-armv7l"]

