build_platform:
  linux_armv7l: linux_armv7l
provider:
  linux_armv7l: azure
conda_forge_output_validation: true
github:
  user_or_org: e8035669acarmv7
  repo_name: "ctng-compilers-feedstock"
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
channels:
  sources:
    - e8035669acarmv7
    - conda-forge
  targets:
    - ['e8035669acarmv7', 'main']
channel_priority: flexible
remote_ci_setup: "e8035669acarmv7::conda-forge-ci-setup=3"
